import React from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, ArrowRight, CheckCircle2 } from 'lucide-react';
import { ToolPageWrapper } from '../../components/ToolPageWrapper';
import { SEO } from '../../components/SEO';

export const WhatIsUuid: React.FC = () => {
  return (
    <ToolPageWrapper
      title="What is a UUID? A Complete Guide to Unique Identifiers"
      description="UUIDs (GUIDs) are 128-bit unique identifiers used in databases, APIs, and distributed systems. Learn the different versions and when to use each."
      breadcrumbs={[{ label: 'Guides', href: '/guides' }, { label: 'What is a UUID?' }]}
      accentColor="primary"
    >
      <SEO
        title="What is a UUID? Guide to Unique Identifiers (GUID, v4, v7) | KooBrain"
        description="Learn what UUIDs are, how the different versions work, when to use UUID v4 vs v7, what GUIDs are, and how to use UUIDs safely in databases and APIs."
        keywords="what is uuid, uuid explained, uuid v4 guide, guid vs uuid, uuid versions, uuid in database, uuid primary key"
      />

      <article className="mt-8 max-w-3xl space-y-10">

        <section className="bg-primary/5 border border-primary/20 rounded-3xl p-8">
          <div className="flex items-start gap-4">
            <div className="size-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
              <BookOpen className="size-5 text-primary" />
            </div>
            <div>
              <p className="text-on-surface font-bold mb-2">What you'll learn</p>
              <ul className="text-sm text-on-surface-variant space-y-1 leading-relaxed">
                <li>• What a UUID is and why it exists</li>
                <li>• The five UUID versions and when to use each</li>
                <li>• What GUID is and how it relates to UUID</li>
                <li>• UUID in database design: pros and cons</li>
                <li>• UUID v7 and why it matters for modern systems</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-black text-on-surface">What is a UUID?</h2>
          <p className="text-on-surface-variant leading-relaxed">
            A <strong className="text-on-surface">UUID</strong> (Universally Unique Identifier) is a 128-bit value used as a unique identifier. It is represented as a 32-character hexadecimal string arranged in five groups separated by hyphens, in the format <code className="bg-surface-container-highest px-1.5 py-0.5 rounded text-sm">8-4-4-4-12</code>:
          </p>
          <div className="bg-surface-container-highest rounded-2xl p-6">
            <p className="font-mono text-on-surface text-center text-lg tracking-widest">550e8400-e29b-41d4-a716-446655440000</p>
          </div>
          <p className="text-on-surface-variant leading-relaxed">
            The defining property of a UUID is that it can be generated by any system, at any time, without a central authority — and the result is statistically guaranteed to be globally unique. This is invaluable in distributed systems where multiple services or databases need to assign IDs independently without coordinating with each other.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-black text-on-surface">The Five UUID Versions</h2>
          <div className="space-y-3">
            {[
              { v: 'v1', name: 'Time-based', desc: 'Generated from the current timestamp and the MAC address of the generating machine. The time component makes v1 sortable by creation order, but the embedded MAC address creates privacy concerns. Rarely used in new applications.', rec: 'Legacy systems only' },
              { v: 'v2', name: 'DCE Security', desc: 'A variant of v1 that embeds a POSIX UID/GID. Almost never used in practice outside of very specific DCE environments.', rec: 'Avoid' },
              { v: 'v3', name: 'Name-based (MD5)', desc: 'Deterministically generated from a namespace UUID and a name using MD5 hashing. Given the same namespace and name, you always get the same UUID. Used for consistent identifier generation in certain data pipelines.', rec: 'Use v5 instead (SHA-1)' },
              { v: 'v4', name: 'Random', desc: 'Generated entirely from cryptographically random data (122 bits of randomness). The most widely used version. Suitable for database primary keys, session IDs, request trace IDs, and any unique identifier need. Cannot be guessed or predicted.', rec: 'Recommended for most uses' },
              { v: 'v5', name: 'Name-based (SHA-1)', desc: 'Like v3 but uses SHA-1 instead of MD5. Generates a deterministic UUID from a namespace and name. Used when you need the same input to always produce the same UUID (e.g., canonical IDs for URLs or email addresses).', rec: 'For deterministic IDs' },
            ].map(v => (
              <div key={v.v} className="p-4 rounded-2xl border border-outline-variant/20 bg-surface-container-low">
                <div className="flex items-center gap-2 mb-2 flex-wrap">
                  <code className="text-xs bg-primary/10 text-primary px-2 py-0.5 rounded-full font-mono">UUID {v.v}</code>
                  <span className="font-bold text-on-surface text-sm">{v.name}</span>
                  <span className="text-xs text-on-surface-variant bg-surface-container-highest px-2 py-0.5 rounded-full ml-auto">{v.rec}</span>
                </div>
                <p className="text-sm text-on-surface-variant leading-relaxed">{v.desc}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-black text-on-surface">UUID v7: The Modern Standard</h2>
          <p className="text-on-surface-variant leading-relaxed">
            UUID v7 is a newer version (RFC 9562, 2024) that combines a millisecond-precision Unix timestamp with random data. This makes UUID v7 values <strong className="text-on-surface">time-ordered</strong> — UUIDs generated later sort after UUIDs generated earlier. This is a major improvement over v4 for database use, because:
          </p>
          <ul className="space-y-2">
            {[
              'Sequential inserts avoid page fragmentation in B-tree indexes',
              'IDs naturally sort by creation time without a separate created_at column',
              'Database index performance is similar to auto-increment integers',
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-2 text-on-surface-variant text-sm leading-relaxed">
                <CheckCircle2 className="size-4 text-primary mt-0.5 shrink-0" />
                {item}
              </li>
            ))}
          </ul>
          <p className="text-on-surface-variant leading-relaxed">
            For new applications starting with UUIDs as primary keys, UUID v7 is the recommended choice. For existing systems already using v4, the migration cost typically outweighs the benefit.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-black text-on-surface">UUID vs GUID: Are They Different?</h2>
          <p className="text-on-surface-variant leading-relaxed">
            <strong className="text-on-surface">GUID</strong> (Globally Unique Identifier) is Microsoft's name for the same concept. GUIDs follow the same RFC 4122 specification as UUIDs and are formatted identically. The only difference is naming convention: Microsoft uses GUID in Windows APIs and .NET; the broader industry uses UUID. They are fully interchangeable — a UUID v4 value is a valid GUID and vice versa.
          </p>
          <p className="text-on-surface-variant leading-relaxed">
            You may also see GUIDs written with curly braces in Windows contexts: <code className="bg-surface-container-highest px-1.5 py-0.5 rounded text-sm">{'{550e8400-e29b-41d4-a716-446655440000}'}</code>. This is a formatting convention only; the actual identifier is the same 128-bit value.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-black text-on-surface">Using UUIDs as Database Primary Keys</h2>
          <p className="text-on-surface-variant leading-relaxed">
            UUIDs are popular as primary keys because they can be generated client-side before inserting a record, enabling optimistic inserts and offline-first patterns. However, there are tradeoffs to understand:
          </p>
          <div className="grid sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-2xl bg-secondary/5 border border-secondary/20">
              <p className="font-bold text-secondary text-sm mb-2">Advantages</p>
              <ul className="text-xs text-on-surface-variant space-y-1.5 leading-relaxed">
                <li>• Generated without database round-trip</li>
                <li>• Safe to expose in URLs (no sequential enumeration)</li>
                <li>• Works across distributed shards and services</li>
                <li>• Merge-friendly for offline/sync scenarios</li>
              </ul>
            </div>
            <div className="p-4 rounded-2xl bg-error/5 border border-error/20">
              <p className="font-bold text-error text-sm mb-2">Tradeoffs</p>
              <ul className="text-xs text-on-surface-variant space-y-1.5 leading-relaxed">
                <li>• 16 bytes vs 4 bytes for an integer — larger indexes</li>
                <li>• UUID v4 causes index fragmentation (random inserts)</li>
                <li>• Less human-readable in logs and debugging</li>
                <li>• Mitigated by UUID v7 for new systems</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="rounded-3xl border border-primary/20 bg-gradient-to-br from-primary/8 via-surface-container to-surface-container-high p-8 flex flex-col sm:flex-row items-start sm:items-center gap-6">
          <div className="flex-1">
            <h3 className="text-lg font-black text-on-surface mb-1">Generate UUID v4 values instantly</h3>
            <p className="text-sm text-on-surface-variant">Use KooBrain's UUID Generator to produce cryptographically secure UUID v4 values — single or bulk — ready to use in your application.</p>
          </div>
          <Link to="/uuid-generator" className="inline-flex items-center gap-2 rounded-2xl bg-primary px-5 py-3 font-extrabold text-on-primary hover:opacity-90 transition-opacity text-sm shrink-0">
            UUID Generator <ArrowRight className="size-4" />
          </Link>
        </section>

        <div className="pt-2">
          <Link to="/guides" className="inline-flex items-center gap-2 text-sm font-black text-on-surface-variant hover:text-primary transition-colors">
            ← Back to all guides
          </Link>
        </div>

      </article>
    </ToolPageWrapper>
  );
};
