import React from "react";
import { Link } from "react-router-dom";
import { AlertTriangle, Scale, Info } from "lucide-react";
import { SEO } from "@/src/components/SEO";
import { ToolPageWrapper } from "@/src/components/ToolPageWrapper";
import { useI18n } from "@/src/i18n/I18nContext";

export const Disclaimer: React.FC = () => {
  const { t } = useI18n();
  return (
    <ToolPageWrapper
      title={t("legal.disclaimer.title")}
      description={t("legal.disclaimer.description")}
      breadcrumbs={[{ label: t("legal.breadcrumb"), href: "#" }, { label: t("legal.disclaimer.title") }]}
      accentColor="error"
    >
      <SEO
        title={t("legal.disclaimer.seo_title")}
        description={t("legal.disclaimer.seo_desc")}
        keywords="disclaimer, koobrain disclaimer, no warranty, limitation of liability"
      />

      <div className="mt-8 grid lg:grid-cols-12 gap-8 animate-fade-in">
        <div className="lg:col-span-8 space-y-8">
          {/* General Disclaimer */}
          <section className="bg-surface-container-lowest border border-outline-variant/30 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface flex items-center gap-3 mb-6">
              <AlertTriangle className="size-7 text-error" />
              General Disclaimer
            </h2>
            <div className="space-y-4 text-on-surface-variant leading-relaxed">
              <p className="text-base">
                This website and all tools provided by Koobrain ("the Website") are provided "AS-IS" without any representations, warranties, or conditions of any kind, either express or implied. While we strive to provide accurate and reliable tools, <span className="text-error font-bold">we make no guarantee regarding accuracy, completeness, or fitness for any particular purpose.</span>
              </p>
              <div className="bg-error/10 border border-error/20 rounded-lg p-4">
                <p className="text-sm font-bold text-on-surface mb-2">⚠️ Important Notice:</p>
                <p className="text-sm">By using Koobrain, you acknowledge that you are solely responsible for verifying the accuracy and appropriateness of any results generated by our tools before relying on them.</p>
              </div>
            </div>
          </section>

          {/* No Warranty */}
          <section className="bg-surface-container-lowest border border-outline-variant/30 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface mb-6">No Warranty</h2>
            <div className="space-y-4 text-on-surface-variant leading-relaxed">
              <p className="text-base">
                Koobrain provides all tools and services without any warranties, express or implied, including but not limited to:
              </p>
              <div className="grid gap-2 mt-4">
                <div className="border border-warning/30 bg-warning/5 rounded-lg p-3">
                  <p className="text-sm font-semibold text-on-surface">Merchantability</p>
                  <p className="text-xs text-on-surface-variant">We do not warrant that tools are suitable for your intended purpose</p>
                </div>
                <div className="border border-warning/30 bg-warning/5 rounded-lg p-3">
                  <p className="text-sm font-semibold text-on-surface">Non-Infringement</p>
                  <p className="text-xs text-on-surface-variant">Results may not be free from third-party claims or patent infringement</p>
                </div>
                <div className="border border-warning/30 bg-warning/5 rounded-lg p-3">
                  <p className="text-sm font-semibold text-on-surface">Availability</p>
                  <p className="text-xs text-on-surface-variant">The Website may be unavailable due to maintenance or technical issues</p>
                </div>
                <div className="border border-warning/30 bg-warning/5 rounded-lg p-3">
                  <p className="text-sm font-semibold text-on-surface">Accuracy</p>
                  <p className="text-xs text-on-surface-variant">Conversions may contain errors or inaccuracies</p>
                </div>
              </div>
            </div>
          </section>

          {/* Tool-Specific Disclaimers */}
          <section className="bg-surface-container-lowest border border-outline-variant/30 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface mb-6">Tool-Specific Disclaimers</h2>
            <div className="space-y-5 text-on-surface-variant leading-relaxed">
              <div className="border-l-4 border-primary pl-4">
                <p className="text-sm font-bold text-on-surface mb-2">📊 Data Format Tools (JSON, CSV, XML)</p>
                <p className="text-sm">Results should be independently validated. Format conversion may introduce minor formatting changes or data loss depending on the source format. Always backup original data before conversion.</p>
              </div>
              <div className="border-l-4 border-secondary pl-4">
                <p className="text-sm font-bold text-on-surface mb-2">🔐 Base64 & Encryption Tools</p>
                <p className="text-sm">These tools are not suitable for securing sensitive data. For encryption, use dedicated security applications. Base64 encoding is not encryption and does not provide security.</p>
              </div>
              <div className="border-l-4 border-tertiary pl-4">
                <p className="text-sm font-bold text-on-surface mb-2">📁 File Conversion Tools</p>
                <p className="text-sm">Converted files may lose formatting, embedded media, or advanced features from the original format. Complex documents may require professional conversion tools for perfect accuracy.</p>
              </div>
              <div className="border-l-4 border-error pl-4">
                <p className="text-sm font-bold text-on-surface mb-2">⚖️ Legal & Medical References</p>
                <p className="text-sm">Tools related to legal calculations or medical conversions are not professional advice. Always consult qualified professionals (lawyers, doctors) before making decisions based on these results.</p>
              </div>
              <div className="border-l-4 border-success pl-4">
                <p className="text-sm font-bold text-on-surface mb-2">💰 Financial Calculations</p>
                <p className="text-sm">Interest calculations, tax tools, and financial conversions are estimates only. Results do not account for all real-world variables. Consult a financial advisor or accountant for actual financial planning.</p>
              </div>
            </div>
          </section>

          {/* Limitation of Liability */}
          <section className="bg-surface-container-lowest border border-outline-variant/30 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface flex items-center gap-3 mb-6">
              <Scale className="size-7 text-secondary" />
              Limitation of Liability
            </h2>
            <div className="space-y-4 text-on-surface-variant leading-relaxed">
              <p className="text-base font-bold text-on-surface">
                To the maximum extent permitted by applicable law, Koobrain shall not be liable for:
              </p>
              <ul className="space-y-2 text-sm ml-4 list-disc">
                <li><span className="font-semibold text-on-surface">Indirect Damages:</span> Lost profits, revenue, data, or business opportunities</li>
                <li><span className="font-semibold text-on-surface">Consequential Damages:</span> Damages resulting from use or inability to use the Website</li>
                <li><span className="font-semibold text-on-surface">Incidental Damages:</span> Costs of substitute goods or services</li>
                <li><span className="font-semibold text-on-surface">Third-Party Claims:</span> Claims arising from third-party content or services</li>
              </ul>
              <p className="text-base mt-6 bg-error/5 border border-error/20 rounded-lg p-4 text-sm">
                <span className="font-bold text-on-surface">Maximum Liability:</span> Our maximum liability for all claims arising from your use of Koobrain is limited to $100 USD or the amount you paid to us, whichever is less. Some jurisdictions do not allow limitation of liability, so this may not apply to you.
              </p>
            </div>
          </section>

          {/* Third-Party Content & Links */}
          <section className="bg-surface-container-lowest border border-outline-variant/30 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface flex items-center gap-3 mb-6">
              <Info className="size-7 text-tertiary" />
              Third-Party Content & External Links
            </h2>
            <div className="space-y-5 text-on-surface-variant leading-relaxed">
              <p className="text-base">
                Koobrain may contain links to external websites owned and operated by third parties. We are not responsible for the content, accuracy, legality, or practices of these external sites. <span className="font-bold text-on-surface">Your use of external links is at your own risk.</span>
              </p>
              <div className="bg-tertiary/5 border border-tertiary/20 rounded-lg p-4 space-y-3">
                <p className="text-sm font-bold text-on-surface">Third-Party Responsibilities:</p>
                <ul className="text-xs space-y-1 ml-3 list-disc text-on-surface-variant">
                  <li>We do not endorse or verify third-party websites or services</li>
                  <li>External sites have their own privacy policies and terms</li>
                  <li>We are not liable for third-party content or services</li>
                  <li>Any dealings with third parties are between you and them</li>
                </ul>
              </div>
              <p className="text-base">
                If you find inappropriate or unauthorized third-party links, please <Link to="/contact" className="text-primary font-bold hover:underline">report them to us</Link>.
              </p>
            </div>
          </section>

          {/* Google AdSense */}
          <section className="bg-surface-container-lowest border border-outline-variant/30 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface mb-6">Google AdSense Disclaimer</h2>
            <div className="space-y-4 text-on-surface-variant leading-relaxed">
              <p className="text-base">
                Koobrain uses Google AdSense to display contextual advertisements. We are not responsible for:
              </p>
              <ul className="space-y-2 text-sm ml-4 list-disc">
                <li>The content or accuracy of advertisements displayed</li>
                <li>Third-party advertisers or their products/services</li>
                <li>Your interactions with advertisements</li>
              </ul>
              <p className="text-base mt-4">
                Google's ad policies govern the advertisements displayed. For more information, visit <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-tertiary font-bold hover:underline">Google's Privacy Policy</a>. You can control your ad preferences in your Google Account settings.
              </p>
            </div>
          </section>

          {/* User Responsibility */}
          <section className="bg-surface-container-lowest border border-outline-variant/30 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface mb-6">User Responsibility</h2>
            <div className="space-y-4 text-on-surface-variant leading-relaxed">
              <p className="text-base font-bold text-on-surface">
                You are solely responsible for your use of Koobrain:
              </p>
              <ul className="space-y-3 text-sm">
                <li className="flex gap-3">
                  <span className="font-bold text-primary shrink-0">→</span>
                  <span><span className="font-semibold text-on-surface">Verification:</span> Always independently verify results before relying on them, especially for critical applications</span>
                </li>
                <li className="flex gap-3">
                  <span className="font-bold text-primary shrink-0">→</span>
                  <span><span className="font-semibold text-on-surface">Compliance:</span> Ensure your use complies with all applicable laws and regulations</span>
                </li>
                <li className="flex gap-3">
                  <span className="font-bold text-primary shrink-0">→</span>
                  <span><span className="font-semibold text-on-surface">Data Protection:</span> Don't use our tools to process sensitive personal data unless properly authorized</span>
                </li>
                <li className="flex gap-3">
                  <span className="font-bold text-primary shrink-0">→</span>
                  <span><span className="font-semibold text-on-surface">Professional Advice:</span> For legal, medical, or financial matters, consult qualified professionals</span>
                </li>
              </ul>
            </div>
          </section>

          {/* Changes to Disclaimer */}
          <section className="bg-surface-container-lowest border border-outline-variant/30 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface mb-6">Changes to This Disclaimer</h2>
            <div className="space-y-4 text-on-surface-variant leading-relaxed">
              <p className="text-base">
                We may update this Disclaimer from time to time to reflect changes in our services, technology, or legal requirements. The date of the last update is posted below. Your continued use of Koobrain following these changes constitutes acceptance of the updated Disclaimer.
              </p>
              <p className="text-sm bg-surface-variant p-4 rounded-lg">
                <span className="font-bold text-on-surface">Last Updated:</span> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
              </p>
            </div>
          </section>

          {/* Questions & Support */}
          <section className="bg-gradient-to-r from-error/10 to-warning/10 border border-outline-variant/20 px-10 py-12 rounded-[2.5rem] shadow-sm">
            <h2 className="text-2xl font-black text-on-surface mb-6">Questions About This Disclaimer?</h2>
            <p className="text-on-surface-variant mb-6 leading-relaxed">
              If you have questions or concerns about this Disclaimer, please contact us at <a href="mailto:nsnathan15@yahoo.com" className="text-primary font-bold hover:underline">nsnathan15@yahoo.com</a> or use our contact form.
            </p>
            <div className="space-y-3">
              <p className="text-base">
                Related legal documents: <Link to="/privacy" className="text-primary font-bold hover:underline">Privacy Policy</Link> and <Link to="/terms" className="text-primary font-bold hover:underline">Terms of Service</Link>
              </p>
              <Link to="/contact" className="inline-flex items-center gap-2 px-8 py-4 bg-error text-on-error rounded-2xl font-bold hover:scale-105 transition-transform">
                Contact Us
              </Link>
            </div>
          </section>
        </div>

        {/* Sidebar */}
        <aside className="lg:col-span-4">
          <div className="bg-surface-container-lowest border border-outline-variant/30 p-6 rounded-[2rem] sticky top-24 space-y-5">
            <h3 className="text-lg font-black text-on-surface">Legal Documents</h3>
            <div className="space-y-3">
              <Link to="/terms" className="flex items-center gap-2 rounded-lg border border-outline-variant/30 bg-surface-container-low px-4 py-3 font-bold text-on-surface hover:bg-surface-variant/40 transition-colors">
                Terms of Service
              </Link>
              <Link to="/privacy" className="flex items-center gap-2 rounded-lg border border-outline-variant/30 bg-surface-container-low px-4 py-3 font-bold text-on-surface hover:bg-surface-variant/40 transition-colors">
                Privacy Policy
              </Link>
              <Link to="/contact" className="flex items-center gap-2 rounded-lg border border-outline-variant/30 bg-surface-container-low px-4 py-3 font-bold text-on-surface hover:bg-surface-variant/40 transition-colors">
                Contact Support
              </Link>
            </div>
            <div className="mt-6 pt-6 border-t border-outline-variant/30">
              <p className="text-xs font-bold text-on-surface-variant mb-3">⚠️ Remember:</p>
              <p className="text-xs text-on-surface-variant leading-dense">Always verify results independently and consult professionals for critical decisions.</p>
            </div>
          </div>
        </aside>
      </div>
    </ToolPageWrapper>
  );
};
