

export type ToolCategory =
  | 'developer'
  | 'image'
  | 'text'
  | 'calculator'
  | 'security'
  | 'json'
  | 'encoding'
  | 'pdf'
  | 'productivity';

export type Tool = {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: ToolCategory;
  path: string;
  trending?: boolean;
};

export const TOOLS: Tool[] = [
  // --- Image Tools ---
  {
    id: 'base64-to-image',
    name: 'Base64 → Image',
    description: 'Convert Base64 strings back to images.',
    icon: 'file-image',
    category: 'image',
    path: '/base64-to-image',
  },
  {
    id: 'image-size-converter',
    name: 'Image Resizer & KB Converter',
    description: 'Resize images to precise dimensions and compress them to a specific KB size instantly.',
    icon: 'image',
    category: 'image',
    path: '/image-size-converter',
  },
  // --- JSON Tools ---
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Clean, prettify, and validate your JSON data instantly with syntax highlighting.',
    icon: 'code-xml',
    category: 'json',
    path: '/json-formatter',
    trending: true,
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript Generator',
    description: 'Convert JSON data into TypeScript interfaces instantly. Perfect for developers building APIs with React, Angular, or Node.js.',
    icon: 'file-code',
    category: 'json',
    path: '/json-to-typescript'
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description: 'Validate your JSON data for errors and correctness.',
    icon: 'code-xml',
    category: 'json',
    path: '/json-validator',
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    description: 'Minify JSON data to reduce file size and remove whitespace.',
    icon: 'code-xml',
    category: 'json',
    path: '/json-minifier',
  },
  {
    id: 'json-pretty-print',
    name: 'JSON Pretty Print',
    description: 'Format and pretty print your JSON for easy reading.',
    icon: 'code-xml',
    category: 'json',
    path: '/json-pretty-print',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON data to CSV format for spreadsheets.',
    icon: 'database',
    category: 'json',
    path: '/json-to-csv',
  },
  {
    id: 'json-to-xml',
    name: 'JSON to XML',
    description: 'Convert JSON data to XML format.',
    icon: 'code-xml',
    category: 'json',
    path: '/json-to-xml',
  },
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML',
    description: 'Convert JSON data to YAML format.',
    icon: 'code-xml',
    category: 'json',
    path: '/json-to-yaml',
  },
  {
    id: 'json-to-html-table',
    name: 'JSON to HTML Table',
    description: 'Convert JSON data to an HTML table for easy viewing.',
    icon: 'database',
    category: 'json',
    path: '/json-to-html-table',
  },
  {
    id: 'json-compare',
    name: 'JSON Compare',
    description: 'Compare two JSON objects and highlight the differences.',
    icon: 'git-compare',
    category: 'json',
    path: '/json-compare',
  },
  {
    id: 'json-sort-keys',
    name: 'JSON Sort Keys',
    description: 'Sort the keys in your JSON objects alphabetically.',
    icon: 'code-xml',
    category: 'json',
    path: '/json-sort-keys',
  },

  // --- Encoding / Decoding Tools ---
  {
    id: 'base64-encode',
    name: 'Base64 Encode',
    description: 'Encode text or files to Base64 format.',
    icon: 'type',
    category: 'encoding',
    path: '/base64-encode',
  },
  {
    id: 'base64-decode',
    name: 'Base64 Decode',
    description: 'Decode Base64 strings back to text or files.',
    icon: 'type',
    category: 'encoding',
    path: '/base64-decode',
  },
  {
    id: 'url-encode',
    name: 'URL Encode',
    description: 'Encode URLs to make them safe for transmission.',
    icon: 'type',
    category: 'encoding',
    path: '/url-encode',
  },
  {
    id: 'url-decode',
    name: 'URL Decode',
    description: 'Decode encoded URLs back to their original form.',
    icon: 'type',
    category: 'encoding',
    path: '/url-decode',
  },
  {
    id: 'html-encode',
    name: 'HTML Encode decode',
    description: 'Encode HTML entities to prevent XSS and display code. Decode HTML entities back to readable text.',
    icon: 'type',
    category: 'encoding',
    path: '/html-encode',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (JWTs).',
    icon: 'lock',
    category: 'encoding',
    path: '/jwt-decoder',
  },
  {
    id: 'text-to-base64',
    name: 'Text to Base64',
    description: 'Convert plain text to Base64 encoding.',
    icon: 'type',
    category: 'encoding',
    path: '/text-to-base64',
  },
  {
    id: 'unicode-converter',
    name: 'Unicode Converter',
    description: 'Convert text to Unicode and vice versa.',
    icon: 'type',
    category: 'encoding',
    path: '/unicode-converter',
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Instantly convert your text to UPPERCASE, lowercase, Title Case, camelCase, snake_case, and more.',
    icon: 'type',
    category: 'text',
    path: '/text-case-converter',
    trending: true,
  },
  {
    id: 'string-comparison',
    name: 'String Comparison',
    description: 'Compare two strings or text blocks and highlight the differences instantly.',
    icon: 'git-compare',
    category: 'developer',
    path: '/string-comparison',
    trending: true,
  },
  {
    id: 'json-converter',
    name: 'JSON Serialize / Deserialize',
    description: 'Convert objects to JSON and JSON to object instantly. Validate and format JSON easily.',
    icon: 'database',
    category: 'developer',
    path: '/json-converter',
    trending: true,
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, random passwords securely.',
    icon: 'lock',
    category: 'security',
    path: '/password-generator',
  },
  {
    id: 'uuid-generator',
    name: 'UUID v4 Generator',
    description: 'Instantly generate cryptographically secure Version 4 UUIDs (Universally Unique Identifiers) in bulk.',
    icon: 'fingerprint',
    category: 'developer',
    path: '/uuid-generator',
    trending: true,
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Real-time word, character, and sentence counting for any text input.',
    icon: 'type',
    category: 'text',
    path: '/word-counter',
    trending: true,
  },
  {
    id: 'pro-image-tool',
    name: 'Pro Image Tool',
    description: 'Advanced image editing and optimization capabilities.',
    icon: 'image',
    category: 'image',
    path: '/pro-image-tool',
    trending: true,
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Beautify complex SQL queries for various dialects.',
    icon: 'database',
    category: 'developer',
    path: '/sql-formatter',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, and days with high precision.',
    icon: 'calendar',
    category: 'calculator',
    path: '/age-calculator',
  },
  {
    id: 'couple-age-calculator',
    name: 'Couple Age Calculator',
    description: 'Calculate the exact age of two people and find their age difference in years, months, and days.',
    icon: 'heart',
    category: 'calculator',
    path: '/couple-age-calculator',
  },
  {
    id: 'time-between-dates',
    name: 'Time Between Dates',
    description: 'Calculate the exact duration between any two dates instantly.',
    icon: 'clock',
    category: 'calculator',
    path: '/time-between-dates',
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Optimize your images with high quality compression. Reduce file size without losing clarity.',
    icon: 'file-image',
    category: 'image',
    path: '/image-compressor',
    trending: true,
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Convert your images into strings instantly for embedding in HTML, CSS, or JSON.',
    icon: 'image',
    category: 'image',
    path: '/image-to-base64',
  },
  {
    id: 'gst-calculator',
    name: 'GST Calculator',
    description: 'Calculate Goods and Services Tax (GST) for any amount instantly. Add or remove GST percentages.',
    icon: 'landmark',
    category: 'calculator',
    path: '/gst-calculator',
  },
  {
    id: 'emi-calculator',
    name: 'EMI Calculator',
    description: 'Calculate Monthly Installments (EMI) for home loans, car loans, and personal loans with interest breakdown.',
    icon: 'banknote',
    category: 'calculator',
    path: '/emi-calculator',
  },

  // --- PDF Tools ---
  {
    id: 'pdf-editor',
    name: 'PDF Editor',
    description: 'Add text annotations and notes to any PDF file. Edit PDF documents directly in your browser with no upload required.',
    icon: 'pen-line',
    category: 'pdf',
    path: '/pdf/editor',
    trending: true,
  },
  {
    id: 'pdf-create',
    name: 'Create PDF',
    description: 'Create a new PDF document from scratch. Type your content and download a professional PDF instantly.',
    icon: 'file-text',
    category: 'pdf',
    path: '/pdf/create',
  },
  {
    id: 'pdf-merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one. Merge PDF documents online free — fast, secure, no watermark.',
    icon: 'layers',
    category: 'pdf',
    path: '/pdf/merge',
    trending: true,
  },
  {
    id: 'pdf-split',
    name: 'Split PDF',
    description: 'Split a PDF into individual pages or extract specific page ranges. Free online PDF splitter.',
    icon: 'scissors',
    category: 'pdf',
    path: '/pdf/split',
  },
  {
    id: 'pdf-add-files',
    name: 'Add Files to PDF',
    description: 'Append pages from another PDF to an existing document. Combine and reorder PDF pages easily.',
    icon: 'file-up',
    category: 'pdf',
    path: '/pdf/add-files',
  },
  {
    id: 'pdf-compress',
    name: 'Compress PDF',
    description: 'Reduce PDF file size without losing quality. Free online PDF compressor — no login required.',
    icon: 'file-image',
    category: 'pdf',
    path: '/pdf/compress',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF files to editable Word documents. Extract text and content from any PDF.',
    icon: 'file-code',
    category: 'pdf',
    path: '/pdf-to-word',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert JPG, PNG, and WebP images into a PDF document. Combine multiple images into one PDF.',
    icon: 'image',
    category: 'pdf',
    path: '/image-to-pdf',
  },
];
